id = "scl"
name = "SCL"
description = "Zed extension for SCL and SCD languages with syntax highlighting and language server integration"
version = "1.0.0"
schema_version = 1
authors = ["Yurii Biurher"]
repository = "https://github.com/ZoralLabs/zed-scl"

[grammars.scl]
repository = "https://github.com/ZoralLabs/tree-sitter-scl"
commit = "main"

[grammars.scd]
repository = "https://github.com/ZoralLabs/tree-sitter-scd"
commit = "main"

[language_servers.scl-lsp]
name = "scl-lsp"
languages = ["scl", "scd"]
