name = "SCL"
grammar = "scl"
path_suffixes = ["scl"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
autoclose_before = ")]},*hWhEtAeIoUaAeIoUaAeIoUaAeIoUaAeIoUaAeIoU"

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "\""
end = "\""
close = true
newline = false
not_in = ["string"]

[[brackets]]
start = "'"
end = "'"
close = true
newline = false
not_in = ["string"]

[language_server]
name = "scl-lsp"
