name = "SCD"
grammar = "scd"
path_suffixes = ["scd"]
line_comments = ["#"]
block_comments = []
autoclose_before = ":.,}])>"
tab_size = 2
hard_tabs = false

# YAML-like language features
word_characters = ["_", "-"]
scope_opt_in_language_servers = ["yaml-language-server"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]

# SCD-specific completion triggers
completion = { trigger_characters = [":", "-", "&", "*"] }

# YAML-aware indentation settings
indent = { kind = "space", size = 2 }
