name = "SCD"
grammar = "scd"
path_suffixes = ["scd"]
line_comments = ["#"]
autoclose_before = ")]},*hWhEtAeIoUaAeIoUaAeIoUaAeIoUaAeIoUaAeIoU"

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "\""
end = "\""
close = true
newline = false
not_in = ["string"]

[[brackets]]
start = "'"
end = "'"
close = true
newline = false
not_in = ["string"]

[language_server]
name = "scl-lsp"

[indent]
unit = "    "

[folding]
start_regex = "^\\s*#\\s*region\\b"
end_regex = "^\\s*#\\s*endregion\\b"
