name = "SCD"
grammar = "scd"
path_suffixes = ["scd"]
line_comments = ["#"]
autoclose_before = ";:.,=}])>"
tab_size = 4
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]
